services:
    typesense:
        image: typesense/typesense:28.0
        container_name: viespirkiai_typesense
        command: "--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors"
        ports:
            - "9021:8108" # Not directly reachable from outside
        volumes:
            - ./typesense/data:/data
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 5048M

    postgres:
        build:
            context: ./postgres
            dockerfile: Dockerfile
        container_name: viespirkiai_postgres
        restart: unless-stopped
        shm_size: "512mb"
        env_file:
            - .env
        ports:
            - "9118:5432" # Not directly reachable from outside
        volumes:
            - ./postgres/pgdata:/var/lib/postgresql/data
        deploy:
            resources:
                limits:
                    memory: 10G

    pgadmin:
        image: dpage/pgadmin4
        container_name: viespirkiai_pgadmin
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "9119:80" # Not directly reachable from outside
        depends_on:
            - postgres
        volumes:
            - ./postgres/pgadmin-data:/var/lib/pgadmin
        deploy:
            resources:
                limits:
                    memory: 2G

    pgbouncer:
        build:
            context: ./pgbouncer
            dockerfile: Dockerfile
        container_name: viespirkiai_pgbouncer
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=postgres
        ports:
            - "9120:6432"
        depends_on:
            - postgres
        deploy:
            resources:
                limits:
                    memory: 256M

    quickwit:
        image: quickwit/quickwit
        container_name: quickwit
        ports:
            - "7280:7280"
        volumes:
            - ./quickwit/qwdata:/quickwit/qwdata
            - ./quickwit/quickwit.yaml:/quickwit/config/quickwit.yaml
        command: run
        environment:
            - QW_DATA_DIR=/quickwit/qwdata
            - QW_CONFIG=/quickwit/config/quickwit.yaml
        restart: unless-stopped
        deploy:
            resources:
                limits:
                  memory: 6g

