export default {
    scrapeProxy: "http://localhost:9102",
    customHead: ``,
    analitikaUrl: "",
    typesenseNodes: [{ host: "localhost", port: 9021, protocol: "http" }],
    typesenseApiKey: "CHANGE_ME",
    typesenseCollection: "viespirkiai",
    typesenseUp: true,
    port: 9019,
    pgHost: "localhost",
    pgUser: "admin",
    pgPassword: "CHANGE_ME",
    pgDatabase: "viespirkiai",
    pgPort: 9118,
    torPassword: "CHANGE_ME",
    pgMaxConnections: 16,
    enableMinification: false,
    workerCount: 2,
    proxyIp: "127.0.0.1",
    torAddress: "socks5h://127.0.0.1:9050",
    dev: false,
    onionAddress: undefined,
    internalFileBase: "https://failai.viespirkiai.org",
    ocrBandymai: 5,
    parallelRouteLoading: true, // false = sequential (easier to debug startup order)
};
