import { syncAdpChanges } from "../modules/adp/syncChanges.js";

// All ADP datasets in one place — add/remove datasets here, not as new task objects
const ADP_DATASETS = [
    {
        name: "syncAdpSaskaitosSalys",
        table: "sabisSaskaituSalys",
        dataset: "datasets/gov/nbfc/viesojo_sektoriaus_saskaitos/SaskaituSalys",
        limit: 1000,
        mapping: {
            _id: "_id", _revision: "_revision",
            id: "id", sf_id: "sfId", tipas: "tipas",
            validus_asmens_kodas: "validusAsmensKodas",
            validus_jar_kodas: "validusJarKodas",
            kitas_kodas: "kitasKodas",
            kitas_kodas_paaiskinimas: "kitasKodasPaaiskinimas",
            pavadinimas: "pavadinimas",
            ne_pvm_moketojas: "nePvmMoketojas",
            veiklos_vieta: "veiklosVieta",
            data: "data",
        },
    },
    {
        name: "syncJarFormos",
        table: "jarFormos",
        dataset: "datasets/gov/rc/jar/formos_statusai/Forma",
        limit: 1000,
        mapping: {
            _id: "_id", _revision: "_revision",
            kodas: "kodas", pavadinimas: "pavadinimas",
            pav_ilgas: "pavIlgas", name: "name",
            tipas: "tipas", type: "type",
        },
    },
    {
        name: "syncAdpSutartysSalys",
        table: "sabisSutarciuSalys",
        dataset: "datasets/gov/nbfc/viesojo_sektoriaus_saskaitos/SutarciuSalys",
        limit: 1000,
        mapping: {
            _type: "_type", _id: "_id", _revision: "_revision",
            id: "id", sutarties_id: "sutartiesId", tipas: "tipas",
            validus_asmens_kodas: "validusAsmensKodas",
            validus_jar_kodas: "validusJarKodas",
            kitas_kodas: "kitasKodas", pavadinimas: "pavadinimas",
            ne_pvm_moketojas: "nePvmMoketojas",
            veiklos_vieta: "veiklosVieta", data: "data",
        },
    },
    {
        name: "syncAdpSabisSaskaitos",
        table: "sabisSaskaitos",
        dataset: "datasets/gov/nbfc/viesojo_sektoriaus_saskaitos/Saskaitos",
        limit: 1000,
        mapping: {
            _id: "_id", _revision: "_revision",
            id: "id", sf_id: "sfId",
            israsymo_data: "israsymoData", sf_pozymis: "sfPozymis",
            sf_tipas: "sfTipas", sf_numeris: "sfNumeris",
            sutarties_uid: "sutartiesUid", sutarties_numeris: "sutartiesNumeris",
            cpv_kodas: "cpvKodas", cpv_pav: "cpvPav",
            sf_apmokejimo_terminas: "sfApmokejimoTerminas",
            pvm: "pvm", suma_be_pvm: "sumaBePvm",
            suma_pvm: "sumaPvm", bendra_sf_suma: "bendraSfSuma",
            valiuta: "valiuta", sf_busena: "sfBusena",
            sf_buseno_data: "sfBusenoData",
        },
    },
    {
        name: "syncAdpSabisSutartys",
        table: "sabisSutartys",
        dataset: "datasets/gov/nbfc/viesojo_sektoriaus_saskaitos/Sutartys",
        limit: 500,
        mapping: {
            _type: "_type", _id: "_id", _revision: "_revision",
            sutarties_id: "sutartiesId", sutarties_uid: "sutartiesUid",
            vp_id: "vpId", tipas: "tipas",
            sutarties_numeris: "sutartiesNumeris", pavadinimas: "pavadinimas",
            cpv_kodas: "cpvKodas", cpv_pav: "cpvPav",
            sutarties_pasirasymo_data: "sutartiesPasirasymoData",
            sutarties_galiojimo_data: "sutartiesGaliojimoData",
            suma: "suma",
        },
    },
    {
        name: "syncAdpBalansoAtaskaitos",
        table: "balansoAtaskaitos",
        dataset: "datasets/gov/rc/jar/balanso_ataskaitos/BalansoAtaskaita",
        limit: 2500,
        mapping: {
            _id: "_id",
            "juridinis_asmuo._id": "jarId", "forma._id": "formaId",
            "statusas._id": "statusasId",
            template_id: "templateId", template_name: "templateName",
            standard_id: "standardId", standard_name: "standardName",
            line_type_id: "lineTypeId", line_name: "lineName",
            reiksme: "reiksme",
            laikotarpis_nuo: "laikotarpisNuo", laikotarpis_iki: "laikotarpisIki",
            reg_date: "duomenuData",
        },
    },
    {
        name: "syncAdpGyvenamojiVietove",
        table: "gyvenamosVietoves",
        dataset: "datasets/gov/rc/ar/gyvenamojivietove/GyvenamojiVietove",
        limit: 1000,
        columns: ["_id", "gyvKodas", "tipas", "tipoSantrumpa", "pavadinimasK", "pavadinimas", "seniunija", "savivaldybe", "gyvNuo", "gyvIki"],
        mapping: {
            _id: "_id", gyv_kodas: "gyvKodas", tipas: "tipas",
            tipo_santrumpa: "tipoSantrumpa", pavadinimas_k: "pavadinimasK",
            pavadinimas: "pavadinimas",
            "seniunija._id": "seniunija", "savivaldybe._id": "savivaldybe",
            gyv_nuo: "gyvNuo", gyv_iki: "gyvIki",
        },
    },
    {
        name: "syncAdpIstatinisKapitalas",
        table: "istatinisKapitalas",
        dataset: "datasets/gov/rc/jar/ja_kapitalas/JuridinisAsmuoKapitalas",
        limit: 1000,
        mapping: {
            _id: "_id",
            "juridinis_asmuo._id": "jarId", "forma._id": "formaId",
            data_nuo: "data", reiksme: "reiksme", valiuta: "valiuta",
        },
    },
    {
        name: "syncAdpJadis",
        table: "jadis",
        dataset: "datasets/gov/rc/jadis/dalyviai/Dalyvis",
        limit: 1000,
        mapping: {
            _id: "_id",
            "juridinis_asmuo._id": "jarId", "form_kodas._id": "formaId",
            "stat_statusas._id": "statusasId",
            lr_fiziniai: "lrFiziniai", lr_juridiniai: "lrJuridiniai",
            uzsienio_fiziniai: "uzsienioFiziniai", uzsienio_juridiniai: "uzsienioJuridiniai",
        },
    },
    {
        name: "syncAdpJar",
        table: "jar",
        dataset: "datasets/gov/rc/jar/iregistruoti/JuridinisAsmuo",
        limit: 1000,
        mapping: {
            _id: "_id", ja_kodas: "jarKodas", ja_pavadinimas: "pavadinimas",
            pilnas_adresas: "adresas", "adresas._id": "adresasId",
            reg_data: "registravimoData", isreg_data: "isregistravimoData",
            "forma._id": "formaId", "statusas._id": "statusasId",
            stat_data: "statusasData",
        },
    },
    {
        name: "syncAdpMokesciai",
        table: "mokesciai",
        dataset: "datasets/gov/vmi/ja_mokesciai/Moketojas",
        limit: 1000,
        mapping: {
            _id: "_id", id: "id", "mm_kodas._id": "mm_kodas_id",
            jarKodas: "jarKodas", pavadinimas: "pavadinimas",
            tipas: "formosPavadinimas", "apskritis._id": "apskritis",
            "savivaldybe._id": "savivaldybe",
            metai: "metai", menuo: "menuo", suma: "suma",
            atnaujinta: "duomenuData",
        },
    },
    {
        name: "syncAdpPelnoNuostoliuAtaskaitos",
        table: "pelnoNuostoliuAtaskaitos",
        dataset: "datasets/gov/rc/jar/pelno_ataskaitos/PelnoAtaskaita",
        limit: 1000,
        mapping: {
            _id: "_id",
            "juridinis_asmuo._id": "jarId", "forma._id": "formaId",
            "statusas._id": "statusasId",
            template_id: "templateId", template_name: "templateName",
            standard_id: "standardId", standard_name: "standardName",
            line_type_id: "lineTypeId", line_name: "lineName",
            reiksme: "reiksme",
            laikotarpis_nuo: "laikotarpisNuo", laikotarpis_iki: "laikotarpisIki",
            reg_date: "duomenuData",
        },
    },
    {
        name: "syncAdpDarboVieta",
        table: "darboVieta",
        dataset: "datasets/gov/uzt/ldv/Vieta",
        limit: 1000,
        mapping: {
            _type: "_type", _id: "_id", _revision: "_revision",
            darbo_vietos_id: "darbo_vietos_id", statusas: "statusas",
            ikelimo_data: "ikelimo_data", galioja_nuo: "galioja_nuo",
            galioja_iki: "galioja_iki",
            imones_iregistravimas: "imones_iregistravimas",
            prelim_darbo_uzmokestis: "prelim_darbo_uzmokestis",
            vid_darbo_uzmokestis: "vid_darbo_uzmokestis",
            maks_darbo_uzmokestis: "maks_darbo_uzmokestis",
            valiuta: "valiuta",
            uzmokescio_komentaras_lt: "uzmokescio_komentaras_lt",
            profesijos_pareigybes_pav: "profesijos_pareigybes_pav",
            darbo_aprasymas_lt: "darbo_aprasymas_lt",
            ar_aktuali_siandien: "ar_aktuali_siandien",
            ar_uzpildyta: "ar_uzpildyta",
            ar_papildomai_remia: "ar_papildomai_remia",
            ar_darbina_po_mokymu: "ar_darbina_po_mokymu",
            ar_apmoka_keliones: "ar_apmoka_keliones",
            ar_apgyvendina: "ar_apgyvendina",
            ar_maitina: "ar_maitina",
            pageidaujama_darbo_pradzia: "pageidaujama_darbo_pradzia",
            darbo_vietu_skaicius: "darbo_vietu_skaicius",
            darbo_vietos_adresas: "darbo_vietos_adresas",
            darbo_vietos_sav_pav: "darbo_vietos_sav_pav",
            registravimo_pagrindo_pav: "registravimo_pagrindo_pav",
            registravimo_budo_pav: "registravimo_budo_pav",
            pageidavimo_pateikimo_pav: "pageidavimo_pateikimo_pav",
            rizikos_lt: "rizikos_lt",
            jar_kodas: "jar_kodas", darbdavys: "darbdavys",
            teisinio_statuso_pav: "teisinio_statuso_pav",
            teisines_formos_pav: "teisines_formos_pav",
            darbdavio_bustine: "darbdavio_bustine",
            darbdavio_kontaktinis_asmuo: "darbdavio_kontaktinis_asmuo",
            susisiekimo_budas: "susisiekimo_budas",
            darbdavio_tel_nr: "darbdavio_tel_nr",
            darbdavio_mob_nr: "darbdavio_mob_nr",
            darbdavio_el_pastas: "darbdavio_el_pastas",
            reik_darbo_patirtis: "reik_darbo_patirtis",
            reik_kompetencijos_lt: "reik_kompetencijos_lt",
            reik_gebejimai: "reik_gebejimai",
            reik_issilavinimo_pav: "reik_issilavinimo_pav",
            reik_mok_progr_pav: "reik_mok_progr_pav",
        },
    },
];

export default ADP_DATASETS.map((cfg) => ({
    name: cfg.name,
    mode: "asap",
    priority: 4,
    cooldown: 60,
    errorCooldown: 60,
    job: () => syncAdpChanges(cfg),
}));
