import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { postgres } from "../postgres/postgres.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const OUTPUT_DIR = path.resolve(__dirname, "../dbSchema");

function quoteIdentifier(value) {
    return `"${String(value).replace(/"/g, "\"\"")}"`;
}

function qualifiedName(schemaName, tableName) {
    return `${quoteIdentifier(schemaName)}.${quoteIdentifier(tableName)}`;
}

function formatDefault(expression) {
    return expression ? ` DEFAULT ${expression}` : "";
}

function formatNullability(isNotNull) {
    return isNotNull ? " NOT NULL" : "";
}

function formatIdentity(identityKind) {
    if (identityKind === "a") return " GENERATED ALWAYS AS IDENTITY";
    if (identityKind === "d") return " GENERATED BY DEFAULT AS IDENTITY";
    return "";
}

function formatGenerated(generatedKind, expression) {
    if (generatedKind !== "s" || !expression) return "";
    return ` GENERATED ALWAYS AS (${expression}) STORED`;
}

async function getTables() {
    const { rows } = await postgres.query(`
        SELECT n.nspname AS schema_name, c.relname AS table_name
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r', 'p')
          AND n.nspname NOT IN ('pg_catalog', 'information_schema')
          AND n.nspname NOT LIKE 'pg_toast%'
        ORDER BY n.nspname, c.relname
    `);

    return rows;
}

async function getColumns(schemaName, tableName) {
    const { rows } = await postgres.query(
        `
        SELECT
            a.attname AS column_name,
            pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
            a.attnotnull AS is_not_null,
            a.attidentity AS identity_kind,
            a.attgenerated AS generated_kind,
            pg_get_expr(ad.adbin, ad.adrelid) AS default_expression
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pg_attrdef ad
               ON ad.adrelid = a.attrelid
              AND ad.adnum = a.attnum
        WHERE n.nspname = $1
          AND c.relname = $2
          AND a.attnum > 0
          AND NOT a.attisdropped
        ORDER BY a.attnum
        `,
        [schemaName, tableName],
    );

    return rows;
}

async function getConstraints(schemaName, tableName) {
    const { rows } = await postgres.query(
        `
        SELECT
            con.conname AS constraint_name,
            con.contype AS constraint_type,
            pg_get_constraintdef(con.oid, true) AS constraint_definition
        FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1
          AND c.relname = $2
        ORDER BY
            CASE con.contype
                WHEN 'p' THEN 1
                WHEN 'u' THEN 2
                WHEN 'f' THEN 3
                WHEN 'c' THEN 4
                WHEN 'x' THEN 5
                ELSE 10
            END,
            con.conname
        `,
        [schemaName, tableName],
    );

    return rows;
}

async function getIndexes(schemaName, tableName) {
    const { rows } = await postgres.query(
        `
        SELECT
            idx.relname AS index_name,
            i.indisprimary AS is_primary,
            pg_get_indexdef(i.indexrelid) AS index_definition
        FROM pg_index i
        JOIN pg_class tbl ON tbl.oid = i.indrelid
        JOIN pg_namespace n ON n.oid = tbl.relnamespace
        JOIN pg_class idx ON idx.oid = i.indexrelid
        WHERE n.nspname = $1
          AND tbl.relname = $2
        ORDER BY i.indisprimary DESC, idx.relname
        `,
        [schemaName, tableName],
    );

    return rows.filter((row) => !row.is_primary);
}

function renderTableSql(schemaName, tableName, columns, constraints, indexes) {
    const tableRef = qualifiedName(schemaName, tableName);
    const columnLines = columns.map((column) => {
        const definition = [
            `${quoteIdentifier(column.column_name)} ${column.data_type}`,
            formatGenerated(column.generated_kind, column.default_expression),
            column.generated_kind === "s"
                ? ""
                : formatIdentity(column.identity_kind),
            column.generated_kind === "s"
                ? ""
                : formatDefault(column.default_expression),
            formatNullability(column.is_not_null),
        ]
            .filter(Boolean)
            .join("");

        return `    ${definition}`;
    });

    const constraintLines = constraints.map(
        (constraint) =>
            `ALTER TABLE ONLY ${tableRef}\n    ADD CONSTRAINT ${quoteIdentifier(constraint.constraint_name)} ${constraint.constraint_definition};`,
    );

    const indexLines = indexes.map((indexRow) => `${indexRow.index_definition};`);

    return [
        `-- ${schemaName}.${tableName}`,
        `-- Generated by scripts/dumpDbSchema.js on ${new Date().toISOString()}`,
        "",
        `CREATE TABLE ${tableRef} (`,
        `${columnLines.join(",\n")}`,
        ");",
        "",
        ...constraintLines,
        ...(constraintLines.length ? [""] : []),
        ...indexLines,
        "",
    ].join("\n");
}

async function resetOutputDir() {
    await fs.rm(OUTPUT_DIR, { recursive: true, force: true });
    await fs.mkdir(OUTPUT_DIR, { recursive: true });
}

async function writeTableSchema(tableRow) {
    const { schema_name: schemaName, table_name: tableName } = tableRow;
    const [columns, constraints, indexes] = await Promise.all([
        getColumns(schemaName, tableName),
        getConstraints(schemaName, tableName),
        getIndexes(schemaName, tableName),
    ]);

    const fileName = `${schemaName}.${tableName}.sql`;
    const filePath = path.join(OUTPUT_DIR, fileName);
    const sql = renderTableSql(schemaName, tableName, columns, constraints, indexes);

    await fs.writeFile(filePath, sql, "utf8");

    return filePath;
}

async function main() {
    await resetOutputDir();

    const tables = await getTables();
    const files = [];

    for (const tableRow of tables) {
        files.push(await writeTableSchema(tableRow));
    }

    console.log(`Dumped ${files.length} tables into ${OUTPUT_DIR}`);
}

main()
    .catch((error) => {
        console.error("Failed to dump DB schema:", error);
        process.exitCode = 1;
    })
    .finally(async () => {
        await postgres.end();
    });
