services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "9022:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: viespirkiai
      MYSQL_USER: viespirkiai
      MYSQL_PASSWORD: viespirkiai
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "9023:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 2048M
    depends_on:
      - mysql