services:
    db:
#        image: postgres:17
        build: .
        container_name: viespirkiaiPostgres
        env_file:
            - ../.env
        ports:
            - "9118:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        deploy:
          resources:
             limits:
                memory: 9G


    pgadmin:
        image: dpage/pgadmin4
        container_name: viespirkiaiPgadmin
        env_file:
            - ../.env
        ports:
            - "9119:80"
        depends_on:
            - db
        volumes:
            - ./pgadmin-data:/var/lib/pgadmin
        deploy:
          resources:
             limits:
                memory: 2G
