import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { postgres } from "./postgres.js";

// Gyvos DB schemos išrašymas į dbSchema/ (po vieną .sql failą lentelei).
//   npm run db:schema:dump

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = path.resolve(HERE, "../dbSchema");
const GENERATOR = "postgres/dumpSchema.js";

function quoteIdentifier(value) {
    return `"${String(value).replace(/"/g, "\"\"")}"`;
}

function qualifiedName(schemaName, tableName) {
    return `${quoteIdentifier(schemaName)}.${quoteIdentifier(tableName)}`;
}

function formatDefault(expression) {
    return expression ? ` DEFAULT ${expression}` : "";
}

function formatNullability(isNotNull) {
    return isNotNull ? " NOT NULL" : "";
}

function formatIdentity(identityKind) {
    if (identityKind === "a") return " GENERATED ALWAYS AS IDENTITY";
    if (identityKind === "d") return " GENERATED BY DEFAULT AS IDENTITY";
    return "";
}

function formatGenerated(generatedKind, expression) {
    if (generatedKind !== "s" || !expression) return "";
    return ` GENERATED ALWAYS AS (${expression}) STORED`;
}

async function getTables() {
    const { rows } = await postgres.query(`
        SELECT n.nspname AS schema_name, c.relname AS table_name
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r', 'p')
          AND n.nspname NOT IN ('pg_catalog', 'information_schema')
          AND n.nspname NOT LIKE 'pg_toast%'
        ORDER BY n.nspname, c.relname
    `);

    return rows;
}

async function getColumns(schemaName, tableName) {
    const { rows } = await postgres.query(
        `
        SELECT
            a.attname AS column_name,
            pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
            a.attnotnull AS is_not_null,
            a.attidentity AS identity_kind,
            a.attgenerated AS generated_kind,
            pg_get_expr(ad.adbin, ad.adrelid) AS default_expression
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pg_attrdef ad
               ON ad.adrelid = a.attrelid
              AND ad.adnum = a.attnum
        WHERE n.nspname = $1
          AND c.relname = $2
          AND a.attnum > 0
          AND NOT a.attisdropped
        ORDER BY a.attnum
        `,
        [schemaName, tableName],
    );

    return rows;
}

async function getConstraints(schemaName, tableName) {
    const { rows } = await postgres.query(
        `
        SELECT
            con.conname AS constraint_name,
            con.contype AS constraint_type,
            pg_get_constraintdef(con.oid, true) AS constraint_definition
        FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1
          AND c.relname = $2
        ORDER BY
            CASE con.contype
                WHEN 'p' THEN 1
                WHEN 'u' THEN 2
                WHEN 'f' THEN 3
                WHEN 'c' THEN 4
                WHEN 'x' THEN 5
                ELSE 10
            END,
            con.conname
        `,
        [schemaName, tableName],
    );

    return rows;
}

async function getTriggers(schemaName, tableName) {
    const { rows } = await postgres.query(
        `
        SELECT
            t.tgname AS trigger_name,
            pg_get_triggerdef(t.oid, true) AS trigger_definition
        FROM pg_trigger t
        JOIN pg_class c ON c.oid = t.tgrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1
          AND c.relname = $2
          AND NOT t.tgisinternal
        ORDER BY t.tgname
        `,
        [schemaName, tableName],
    );

    return rows;
}

async function getRoutines(schemaName) {
    const { rows } = await postgres.query(
        `
        SELECT
            p.proname AS routine_name,
            pg_get_function_identity_arguments(p.oid) AS identity_args,
            pg_get_functiondef(p.oid) AS routine_definition,
            p.prokind AS routine_kind
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = $1
          AND p.prokind IN ('f', 'p', 'a', 'w')
          AND NOT EXISTS (
              SELECT 1 FROM pg_depend d
              WHERE d.objid = p.oid
                AND d.deptype = 'e'
          )
        ORDER BY p.proname, identity_args
        `,
        [schemaName],
    );

    return rows;
}

async function getIndexes(schemaName, tableName) {
    const { rows } = await postgres.query(
        `
        SELECT
            idx.relname AS index_name,
            i.indisprimary AS is_primary,
            pg_get_indexdef(i.indexrelid) AS index_definition
        FROM pg_index i
        JOIN pg_class tbl ON tbl.oid = i.indrelid
        JOIN pg_namespace n ON n.oid = tbl.relnamespace
        JOIN pg_class idx ON idx.oid = i.indexrelid
        WHERE n.nspname = $1
          AND tbl.relname = $2
        ORDER BY i.indisprimary DESC, idx.relname
        `,
        [schemaName, tableName],
    );

    return rows.filter((row) => !row.is_primary);
}

function renderTableSql(schemaName, tableName, columns, constraints, indexes, triggers) {
    const tableRef = qualifiedName(schemaName, tableName);
    const columnLines = columns.map((column) => {
        const definition = [
            `${quoteIdentifier(column.column_name)} ${column.data_type}`,
            formatGenerated(column.generated_kind, column.default_expression),
            column.generated_kind === "s"
                ? ""
                : formatIdentity(column.identity_kind),
            column.generated_kind === "s"
                ? ""
                : formatDefault(column.default_expression),
            formatNullability(column.is_not_null),
        ]
            .filter(Boolean)
            .join("");

        return `    ${definition}`;
    });

    const constraintLines = constraints.map(
        (constraint) =>
            `ALTER TABLE ONLY ${tableRef}\n    ADD CONSTRAINT ${quoteIdentifier(constraint.constraint_name)} ${constraint.constraint_definition};`,
    );

    const indexLines = indexes.map((indexRow) => `${indexRow.index_definition};`);
    const triggerLines = triggers.map((trigger) => `${trigger.trigger_definition};`);

    return [
        `-- ${schemaName}.${tableName}`,
        `-- Generated by ${GENERATOR} on ${new Date().toISOString()}`,
        "",
        `CREATE TABLE ${tableRef} (`,
        `${columnLines.join(",\n")}`,
        ");",
        "",
        ...constraintLines,
        ...(constraintLines.length ? [""] : []),
        ...indexLines,
        ...(triggerLines.length && indexLines.length ? [""] : []),
        ...triggerLines,
        "",
    ].join("\n");
}

function renderRoutinesSql(schemaName, routines) {
    return [
        `-- ${schemaName} routines (functions/procedures)`,
        `-- Generated by ${GENERATOR} on ${new Date().toISOString()}`,
        "",
        ...routines.flatMap((routine) => [`${routine.routine_definition};`, ""]),
    ].join("\n");
}

async function resetOutputDir() {
    await fs.rm(OUTPUT_DIR, { recursive: true, force: true });
    await fs.mkdir(OUTPUT_DIR, { recursive: true });
}

async function writeTableSchema(tableRow) {
    const { schema_name: schemaName, table_name: tableName } = tableRow;
    const [columns, constraints, indexes, triggers] = await Promise.all([
        getColumns(schemaName, tableName),
        getConstraints(schemaName, tableName),
        getIndexes(schemaName, tableName),
        getTriggers(schemaName, tableName),
    ]);

    const fileName = `${schemaName}.${tableName}.sql`;
    const filePath = path.join(OUTPUT_DIR, fileName);
    const sql = renderTableSql(schemaName, tableName, columns, constraints, indexes, triggers);

    await fs.writeFile(filePath, sql, "utf8");

    return filePath;
}

async function writeRoutines(schemaName) {
    const routines = await getRoutines(schemaName);
    if (!routines.length) return null;

    const fileName = `${schemaName}._routines.sql`;
    const filePath = path.join(OUTPUT_DIR, fileName);
    await fs.writeFile(filePath, renderRoutinesSql(schemaName, routines), "utf8");
    return filePath;
}

async function main() {
    await resetOutputDir();

    const tables = await getTables();
    const files = [];

    for (const tableRow of tables) {
        files.push(await writeTableSchema(tableRow));
    }

    const schemaNames = [...new Set(tables.map((row) => row.schema_name))];
    const routineFiles = [];
    for (const schemaName of schemaNames) {
        const filePath = await writeRoutines(schemaName);
        if (filePath) routineFiles.push(filePath);
    }

    console.log(
        `Dumped ${files.length} tables and ${routineFiles.length} routine files into ${OUTPUT_DIR}`,
    );
}

main()
    .catch((error) => {
        console.error("Failed to dump DB schema:", error);
        process.exitCode = 1;
    })
    .finally(async () => {
        await postgres.end();
    });
