services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "9020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pinigaiibala
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #       cpus: '1'